title: Floreciendo Ciudad
author: Lagos Pi√±a
email: floreciendociudad@gmail.com


description: De parques, banquetas, flores y vecinas.  Ideas sobre la ciudad que habitamos de la voz de una vecina.



# social links
twitter_username: FloreceCiudad # DO NOT include the @ character, or else the build will fail!
github_username:  FloreciendoCiudad # DO NOT include the @ character, or else the build will fail!
instagram_username: floreciendo_ciudad

theme: minima

show_excerpts: true # set to false to remove excerpts on the homepage
